name: Add label to tested issue

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: set rustup profile
      run: |
        rustup self update
        rustup set profile minimal

    - name: Cargo run labeler
      run: cargo run -p labeler
      env:
        LABEL_TOKEN: ${{ secrets.LABEL_TOKEN }}
