name: Add label to tested issue

on:
  push:
    branches:
      - master

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.repository == 'rust-lang/glacier'

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

      - run: ./target/release/labeler
        env:
          LABEL_TOKEN: ${{ secrets.LABEL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
