name: Add label to tested issue

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'rust-lang/glacier'

    steps:
      - uses: actions/checkout@v2

      - name: Configure rustup
        run: |
          rustup set profile minimal
          rustup toolchain install nightly

      - name: Cargo run labeler
        run: cargo run -p labeler
        env:
          LABEL_TOKEN: ${{ secrets.LABEL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
